[tool.black]
line-length = 120
target-version = ["py310", "py311"]

[tool.mypy]
strict = true
python_version = "3.10"
ignore_missing_imports = true
disallow_any_generics = false # python 3.8 compatibility
junit_xml = "reports/mypy.xml"

[tool.ruff]
target-version = "py310"
line-length = 120
select = ["ALL"]
ignore = [
    "ANN101",  # missing-type-self
    "COM",     # trailing-comma
    "D101",    # undocumented-public-class
    "D104",    # undocumented-public-package
    "D105",    # undocumented-magic-method
    "D107",    # undocumented-public-init
    "D203",    # one-blank-line-before-class
    "D213",    # multi-line-summary-second-line
    "I001",    # unsorted-imports
    "INP001",  # implicit-namespace-package
    "TRY400",  # error-instead-of-exception
]
