[tool.black]
line-length = 120
target-version = ["py310", "py311"]

[tool.mypy]
python_version = "3.10"
strict = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
junit_xml = "reports/mypy.xml"
pretty = true
