name: _Code analyse

on:
  workflow_call:

jobs:
  code-analyse:
    name: Code analyse
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo apt install shellcheck

      - name: Check shell scripts
        run: |
          find . -type f -name "*.sh" -not \( -path "./buildroot/*" -prune \) -exec shellcheck --format=gcc {} \;

      - name: Check buildroot-external packages
        run: |
          buildroot/utils/check-package --exclude PackageHeader --br2-external buildroot-external/package/*/*

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Linters
        run: |
          pip install -r requirements.txt
          black --version
          black --diff --check $(git ls-files '*.py')
          mypy --version
          mypy $(git ls-files '*.py')
          ruff --version
          ruff $(git ls-files '*.py')
