name: Build Unipi Control Operation System Image

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/buildroot/buildroot
  REPO_BRANCH: 2022.02.10
  CONFIG_FILE: .config
  TZ: Europe/Vienna

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq upgrade
          sudo apt install wget git bc bison linux-headers-$(uname -r)
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      # https://github.com/actions/virtual-environments/issues/2577
      - name: Blocked mirror workaround
        run: echo "1.1.1.1 invisible-mirror.net" | sudo tee -a /etc/hosts

      - name: Clone buildroot source code
        working-directory: /workdir
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH buildroot_src
          ln -sf /workdir/buildroot_src $GITHUB_WORKSPACE/buildroot_src
      
      - name: Load Unipi Neuron RPi 3B configuration
        run: |
          cd $GITHUB_WORKSPACE/buildroot_src
          make BR2_EXTERNAL=$GITHUB_WORKSPACE/buildroot neuron_rpi3_64_defconfig

      - name: Compile Unipi Neuron RPi 3B sdcard image
        run: |
          cd $GITHUB_WORKSPACE/buildroot
          make clean all

      - name: Upload sdcard image
        uses: actions/upload-artifact@master
        with:
          name: unipi_neuron_rpi3b.img
          path: /workdir/buildroot/output/images/sdcard.img
