name: Release build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  validate_release:
    name: Create build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.result }}
      version: ${{ steps.version_check.outputs.version }}
      os_id: ${{ steps.version_check.outputs.os_id }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Initialization environment
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq upgrade
          sudo apt install shellcheck
      - name: Check shell scripts
        run: |
          for file in $(find buildroot/board -type f -name "*.sh"); do shellcheck --format=gcc $file; done;
          for file in $(find buildroot/package -type f -name "*.sh"); do shellcheck --format=gcc $file; done;
      - name: Validate version
        id: version_check
        run: |
          os_id=$(cat ${GITHUB_WORKSPACE}/buildroot-external/meta | grep OS_ID | cut -d'=' -f2)
          major=$(cat ${GITHUB_WORKSPACE}/buildroot-external/meta | grep VERSION_MAJOR | cut -d'=' -f2)
          build=$(cat ${GITHUB_WORKSPACE}/buildroot-external/meta | grep VERSION_BUILD | cut -d'=' -f2)

          tag_major=$(echo "${{ github.ref_name }}" | cut -d '.' -f 1)
          tag_build=$(echo "${{ github.ref_name }}" | cut -d '.' -f 2)
          tag_dev=$(echo "${{ github.ref_name }}" | cut -d '.' -f 3)

          if [ "${major}.${build}" != "${tag_major}.${tag_build}" ]; then
            echo "Version number in Buildroot metadata is does not match tag (${major}.${build} vs ${{ github.ref_name }})."
            exit 1
          fi

          if [ "${tag_dev}" != "" ]; then
            echo "version=${major}.${build}.${tag_dev}" >> $GITHUB_OUTPUT
          else
            echo "version=${major}.${build}" >> $GITHUB_OUTPUT
          fi

          echo "version_dev=${tag_dev}" >> $GITHUB_OUTPUT
          echo "os_id=${os_id}" >> $GITHUB_OUTPUT
      - name: Create build matrix
        uses: actions/github-script@v6
        id: generate_matrix
        with:
          script: |
            const boards = require("./.github/workflows/matrix.json")
            return { "board": boards }

  build:
    name: Build image for ${{ matrix.board.id }}
    needs:
      - validate_release
    strategy:
      matrix: ${{ fromJson(needs.validate_release.outputs.matrix) }}
    runs-on: ${{ matrix.board.runner }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build docker container
        run: docker build -t ucos-builder .
      - name: Build image
        run: |
          docker run --rm --privileged -v "${GITHUB_WORKSPACE}:/build" ucos-builder \
          make BUILDDIR=/build VERSION_DEV=${{ needs.validate_release.outputs.version_dev }} ${{ matrix.board.defconfig }}
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.validate_release.outputs.os_id }}-${{ matrix.board.id }}-${{ needs.validate_release.outputs.version }}.img.xz
          path: ${{ github.workspace }}/release/${{ needs.validate_release.outputs.os_id }}-${{ matrix.board.id }}-${{ needs.validate_release.outputs.version }}.img.xz

  release:
    name: Release image
    needs:
      - validate_release
      - build
    strategy:
      matrix: ${{ fromJson(needs.validate_release.outputs.matrix) }}
    runs-on: ubuntu-latest
    if: |
      github.event.name != 'workflow_dispatch'
      && needs.validate_release.outputs.version_dev == ''
    steps:
      - name: Download image
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.validate_release.outputs.os_id }}-${{ matrix.board.id }}-${{ needs.validate_release.outputs.version }}.img.xz
      - name: Release image
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.validate_release.outputs.os_id }}-${{ matrix.board.id }}-${{ needs.validate_release.outputs.version }}
          files: ${{ needs.validate_release.outputs.os_id }}-${{ matrix.board.id }}-${{ needs.validate_release.outputs.version }}.img.xz
