name: Test Build Image

on:
  workflow_dispatch:

  push:
    tags:
      - 'test'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME:
    steps:
      - name: Build
        run: |
          echo ${{ github.repository }}
          echo $GITHUB_EVENT_NAME
          echo "${{ github.repository.name }}"
          echo "$GITHUB_REF_NAME" > test.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.repository.name }}-$GITHUB_REF_NAME.txt
          files: test.txt
