name: Test Build Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'test'
      - 'test-pre'

jobs:
  check-tag:
    name: Check git tag
    runs-on: ubuntu-latest
    outputs:
      release-type: ${{ steps.check-tag.outputs.run_jobs }}
    steps:
      - name: check tag ${{ github.ref }}
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs\/tags\/test$ ]]; then
            echo "run_jobs=release" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.ref }} =~ ^refs\/tags\/test-pre$ ]]; then
            echo "run_jobs=prerelease" >> $GITHUB_OUTPUT
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - check-tag
    steps:
      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Build
        run: |
          echo "${GITHUB_REF_NAME}" > ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.txt
          tar -czvf ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.tar.gz ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          github.event.name != 'workflow_dispatch'
          && needs.check-tag.outputs.release-type == 'release'
        with:
          name: ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}
          files: ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.tar.gz
          prerelease: False
      - name: Pre release
        uses: softprops/action-gh-release@v1
        if: |
          github.event.name != 'workflow_dispatch'
          && needs.check-tag.outputs.release-type == 'prerelease'
        with:
          name: ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}
          files: ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.tar.gz
          prerelease: True
