name: Test Build Image

on:
  workflow_dispatch:

  push:
    tags:
      - 'test'

#Run echo unipi-buildroot
#  echo unipi-buildroot
#  echo ${GITHUB_EVENT_NAME}
#  echo ${GITHUB_REF}
#  echo ${GITHUB_REF_NAME}
#  echo "${GITHUB_REF_NAME}" > test.txt
#  shell: /usr/bin/bash -e {0}
#  env:
#    PROJECT_NAME:
#    REPOSITORY_NAME: unipi-buildroot
#unipi-buildroot
#workflow_dispatch
#refs/heads/main
#main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Build
        run: |
          echo "${GITHUB_REF_NAME}" > test.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref.type == 'tag'
        with:
          name: ${{ env.REPOSITORY_NAME }}-${GITHUB_REF_NAME}.txt
          files: test.txt
