name: Test Build Image

on:
  workflow_dispatch:

  push:
    tags:
      - 'test'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME:
    steps:
      - name: Build
        run: |
          echo ${{ github.repository }}
          echo $GITHUB_REPOSITORY
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_REF
          echo GITHUB_REF_NAME
          echo ${{ github.ref_name }} > test.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.repository.name }}-${{ github.ref_name }}.txt
          files: test.txt
