name: Test Build Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'test'
      - 'test-pre'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Build
        run: |
          echo "${GITHUB_REF_NAME}" > ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event.name != 'workflow_dispatch'
        with:
          name: ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}
          files: ${{ env.REPOSITORY_NAME }}-${{ github.ref_name }}.txt
          prerelease: True
