name: Test Build Image

on:
  workflow_dispatch:

  push:
    tags:
      - 'test'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "${{ CI_PIPELINE_SOURCE }}"
          echo "${{ CI_COMMIT_TAG }}" > test.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ CI_PROJECT_NAME }}-${{ CI_COMMIT_TAG }}.txt
          files: test.txt
