name: Test Build Image

on:
  workflow_dispatch:

  push:
    tags:
      - 'test'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "${{ env.GITHUB_EVENT_NAME }}"
          echo "${{ env.github.event.repository.name }}"
          echo "${{ env.GITHUB_REF_NAME }}" > test.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.github.event.repository.name }}-${{ env.GITHUB_REF_NAME }}.txt
          files: test.txt
