name: Test Build Image

on:
  workflow_dispatch:

  push:
    tags:
      - 'test'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME:
    steps:
      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Build
        run: |
          echo ${{ env.REPOSITORY_NAME }}
          echo ${{ github.ref.type }}
          echo ${{ github.ref.name }} > test.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.REPOSITORY_NAME }}-${{ github.ref.name }}.txt
          files: test.txt
