name: Test Build Image

on:
  workflow_dispatch:
  push:
    tags:
      - 'test'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          cat "${{ github.ref }}" > test.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: test-${{ github.ref }}.txt
          files: test.txt
